# Generated by Django 3.1.4 on 2021-01-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=150)),
                ('opening_days', models.CharField(max_length=50)),
                ('opening_hours', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
